services:
  api:
    container_name: items-microservice
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/techchallenge-app/items-microservice
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/techchallenge-app/items-microservice
      - /usr/src/techchallenge-app/items-microservice/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    depends_on:
      - items-database-db
    networks:
      - app-network

  items-database-db:
    image: 'bitnami/postgresql:15'
    container_name: items-database
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=techchallenge
    ports:
      - 5434:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-network

volumes:
  postgresql_data:
    driver: local

networks:
  app-network:
